### ISSUE TITLE
npm install hangs due to grunt-usemin reference

### ISSUE THREAD

**Issue by jsalamin** [evolution7/generator-symfony#11]
I followed the **Getting started** process and everything works well until i execute the command _npm install_ (required for me to complete the installation).

The process hangs without any error message.
## How to fix it

In the root folder of my symfony project, in the file **package.json**, replace this line:
_"grunt-usemin": "git+ssh://git@github.com/yeoman/grunt-usemin.git#v2.0",_
by this one:
_"grunt-usemin": "~2.1.0",_

**Comment by ryan0x44** [comment]
Hey @jsalamin thanks for the report! I believe this issue has been fixed in the 0.4.1 release so I'll close this issue, but please re-open if you find this not to be the case.
