### ISSUE TITLE
grunt build modernizr Warning: Cannot use 'in' operator to search for 'devFile'

### ISSUE THREAD

**Issue by extdevelopment** [evolution7/generator-symfony#19]
grunt build run with warnig:
Warning: Cannot use 'in' operator to search for 'devFile' in web/bower_components/modernizr/modernizr.js Use --force to continue.

solution:
you need to convert the  modernizr task into a multitask & add  "files" : {"src": [] },

Gruntfile.js

<pre>
modernizr: {
            //https://github.com/Modernizr/grunt-modernizr/issues/48#issuecomment-31007556
            dist: {
                devFile: '<%= yeoman.app %>/bower_components/modernizr/modernizr.js',
                outputFile: '<%= yeoman.dist %>/bower_components/modernizr/modernizr.js',
                files:{
                    //https://github.com/Modernizr/grunt-modernizr#config-options
                    src: [
                        '<%= yeoman.dist %>/scripts/{,*/}*.js',
                        '<%= yeoman.dist %>/css/{,*/}*.css',
                        '!<%= yeoman.dist %>/scripts/vendor/*'
                    ]
                },
                uglify: true
            }
        },
</pre>

**Comment by ArjenSchwarz** [comment]
Thanks for letting us know about this. I'll have a look at it next week and will update here once it's been fixed.

**Comment by sweetroll** [comment]
It looks like this issue was caused by grunt-modernizr 0.5.1. If you stick to ~0.3.0 you should not have an issue. We will do a version bump of all npm packages shortly. Thanks!

**Comment by extdevelopment** [comment]
version bump? great, thx:)
