### ISSUE TITLE
Invalid composer.json in master branch

### ISSUE THREAD

**Issue by titomiguelcosta** [evolution7/generator-symfony#8]
Hi, seems the json for composer.json is invalid, missing a comma on line 21, https://raw2.github.com/evolution7/generator-symfony/master/app/templates/symfony/composer.json#

**Comment by ryan0x44** [comment]
Thanks @titomiguelcosta, nice find!

@ArjenSchwarz did this slip through on cc8d4fe9 ?

**Comment by ArjenSchwarz** [comment]
Looks that way, I'll revert that commit within an hour. There are some dependencies that don't work with 2.4 yet either, so that will have to be worked around first anyway. Apologies for that.

**Comment by ArjenSchwarz** [comment]
Ok, I just fixed this in https://github.com/evolution7/generator-symfony/commit/88d44781b6ac88e011c66706afb0afb3d0ca5a8c

Thanks again for spotting this @titomiguelcosta

**Comment by ryan0x44** [comment]
Nice work dude, thanks! :+1:

**Comment by titomiguelcosta** [comment]
thanks, keep up the good work ;)
