### ISSUE TITLE
Installation requires Github ssh key

### ISSUE THREAD

**Issue by ArjenSchwarz** [evolution7/generator-symfony#9]
There is a hardcoded `git+ssh` reference for grunt-usemin in `app/templates/_package.json`. This should be fixed to become an https connection so people don't need to have an ssh configured in Github to be able to use the generator.

**Comment by ryan0x44** [comment]
You could always get around the issue with [this](http://stackoverflow.com/questions/15669091/bower-install-using-only-https):

```
git config --global url."https://".insteadOf git://
```

Although on closer inspection, the [grunt-usemin](https://www.npmjs.org/package/grunt-usemin) package now has v2.0 published, so the troubling line should just be changed to:

```
"grunt-usemin": "~2.0.0",
```

**Comment by ArjenSchwarz** [comment]
Of course there are ways around it, as I told the person who reported it, but it should be also fixed in our code :). 
I'll probably do it after the weekend, but it's good that we can get rid of the hack as well. I wanted to ask you what that was for anyway.

**Comment by ryan0x44** [comment]
Cool. v2.0 was bleeding edge when I first put this together so had to pull it in from the repo. A fix would be great thanks dude!

**Comment by ArjenSchwarz** [comment]
Updated the grunt-usemin requirement in release 0.4.1 so this issue is now fixed.
